### PR TITLE
Changed the way we create the answer provider for dialog editors.

### PR DESCRIPTION
**Pull request by kittaakos**
Signed-off-by: Akos Kitta <kittaakos@typefox.io>

@crapo, I have changed the way we create the answer providers for the dialog editors, I am still having NPEs here and there. Please schedule a remote pair-programming session where we discuss the outstanding issues. Also, I am happy to explain what my changes are.

### CODE REVIEW

**Comment by kittaakos** [comment]
I am also experiencing the same error from the `master`:
```
o.IOException: Number of parameters does not equal the number of equation arguments.
	at com.ge.research.sadl.darpa.aske.curation.AnswerCurationManager.evaluateInComputationalGraph(AnswerCurationManager.java:719)
	at com.ge.research.sadl.darpa.aske.curation.AnswerCurationManager.processEvalRequest(AnswerCurationManager.java:647)
	at com.ge.research.sadl.darpa.aske.curation.AnswerCurationManager.processUserRequest(AnswerCurationManager.java:1431)
	at com.ge.research.sadl.darpa.aske.curation.AnswerCurationManager.processConversation(AnswerCurationManager.java:2316)
	at com.ge.research.sadl.darpa.aske.processing.JenaBasedDialogModelProcessor.onValidate(JenaBasedDialogModelProcessor.java:445)
	at com.ge.research.sadl.validation.ResourceValidator.doValidate(ResourceValidator.java:75)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:71)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:90)
	at com.ge.research.sadl.validation.ResourceValidator.lambda$0(ResourceValidator.java:55)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:76)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:57)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:91)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:26)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:527)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:499)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:137)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.createIssues(ValidationJob.java:86)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.run(ValidationJob.java:67)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by crapo** [comment]
I didn't quite get all of the fixes to issues checked in last night. Let me finish that and then push changes. I think that will resolve some of these issues. Then we can see what is left to discuss.

**Comment by crapo** [comment]
The changed way of instantiating the DialogAnswerProvider looks like a great improvement! And solution to a really annoying problem.

**Comment by kittaakos** [comment]
> Then we can see what is left to discuss.

Sure. No hurry.

**Comment by crapo** [comment]
I have pushed a number of changes/bug fixes to master. When you are ready I am available to talk. Should I merge in the other PR that's ready to merge first?

**Comment by kittaakos** [comment]
> When you are ready I am available to talk

I am ready as well, please send a link.

> Should I merge in the other PR that's ready to merge 

It is up to you. The CA changes are unrelated.

**Comment by kittaakos** [comment]
I added a few fixes, @crapo. I intentionally left the PR in draft mode. Can you please try it and check whether the insertion is better or worse? I could not reproduce the issue with `DialogAnswerProviderConsoleForTest` after my fixes, but I might have overlooked something. Thanks for the help!

**Pull request merged**
